#!/bin/bash

echo "meta down"

DIR_NAME=${DIR_NAME:-$(dirname $(readlink -f $0))}
DIR_NAME=${DIR_NAME:-"."}
source $DIR_NAME/meta-env

[ -f ./meta-down.local ] && source ./meta-down.local

for proxy_user_id in ${PROXY_USER_IDS[@]}
do
    echo "enabling proxy for user $proxy_user_id"
    iptables -t nat -D OUTPUT -m owner --uid-owner $(id -u $proxy_user_id) -p tcp -j $CHAIN_NAME
done

for proxy_lan_ip in ${PROXY_LAN_IPS[@]}
do
    echo "disabling proxy for $proxy_lan_ip"
    iptables -t mangle -D PREROUTING -s $proxy_lan_ip ! -d $proxy_lan_ip -j $CHAIN_NAME
done

echo "removing rule for redirecting to proxy"
iptables -t mangle -F $CHAIN_NAME
iptables -t mangle -X $CHAIN_NAME
iptables -t nat -F $CHAIN_NAME
iptables -t nat -X $CHAIN_NAME

echo "flushing route table"
ip rule del fwmark $MARK_VALUE lookup $ROUTE_TABLE
ip route flush table $ROUTE_TABLE

sleep 1

echo "removing bypass whitelist"
ipset destroy $SET_NAME
