#!/bin/bash
set -e

echo "meta config"

DIR_NAME=${DIR_NAME:-$(dirname $(readlink -f $0))}
DIR_NAME=${DIR_NAME:-"."}
source $DIR_NAME/meta-env

CHOWN="chown -R $USER:$USER ."
if ! $CHOWN 2>/dev/null; then
    echo "No permission, using sudo"
    export USER
    exec sudo --preserve-env=USER "$0" "$@"
    return
fi

export https_proxy=http://$BIND:7890

wget -O remote.yaml $CONFIG_URL

cat <<EOF > config.yaml
EOF
cat remote.yaml >> config.yaml

sed -i "s/^secret: .\+/secret: $PASSWORD/" config.yaml
sed -i "s/^bind-address: .\+/bind-address: $BIND/" config.yaml
sed -i "s/^external-controller: .\+:9090/external-controller: $BIND:9090/" config.yaml
sed -i "s/listen: .\+:53/listen: $DNS_BIND:53/" config.yaml
sed -i 's/enhanced-mode: fake-ip/enhanced-mode: redir-host/' config.yaml

wget -O- --method=PUT --header="Authorization: Bearer $PASSWORD" --body-data='{"path": "", "payload": ""}' "http://$BIND:9090/configs?force=true"

$CHOWN
