#!/bin/bash

DIR_NAME=${DIR_NAME:-$(dirname $(readlink -f $0))}
DIR_NAME=${DIR_NAME:-"."}
echo "meta dir: ${DIR_NAME}"
[ -f $DIR_NAME/.env ] && source $DIR_NAME/.env

cd $DIR_NAME
echo "current working dir: $(pwd)"

OWNER=${OWNER:-$(id -u $(whoami))}

TAILSCALE_IP=${TAILSCALE_IP:-$(tailscale ip -4)}
BIND=${BIND:-0.0.0.0}

CHAIN_NAME=${CHAIN_NAME:-meta}
SET_NAME=${SET_NAME:-meta_bypass}
MARK_VALUE=${MARK_VALUE:-1}
ROUTE_TABLE=${ROUTE_TABLE:-99}
REDIRECT_PORT=${REDIRECT_PORT:-7892}
TPROXY_PORT=${TPROXY_PORT:-7893}
if [ "$BIND" = "0.0.0.0" ]; then
    TPROXY_IP=${TPROXY_IP:-127.0.0.1}
else
    TPROXY_IP=${TPROXY_IP:-${BIND}}
fi
IFS=',:' read -ra BYPASS_IPS <<< "$BYPASS_IPS"
IFS=',:' read -ra PROXY_LAN_IPS <<< "$PROXY_LAN_IPS"

IFS=',:' read -ra PROXY_USERS <<< "$PROXY_USERS"
IFS=',:' read -ra PROXY_USER_IDS <<< "$PROXY_USER_IDS"
for user in "${PROXY_USERS[@]}"; do
    PROXY_USER_IDS+=( $(id -u "$user") )
done

[ -z "$CONFIG_URL" ] && echo "CONFIG_URL not found"

PASSWORD=${PASSWORD:-password}
DNS_BIND=${DNS_BIND:-${TAILSCALE_IP}}
