#!/bin/bash
set -e

echo "meta config"

DIR_NAME=${DIR_NAME:-$(dirname $(readlink -f $0))}
DIR_NAME=${DIR_NAME:-"."}
source $DIR_NAME/meta-env

CHOWN="chown -R $OWNER:$OWNER ."
if ! $CHOWN 2>/dev/null; then
    echo "No permission, using sudo"
    export OWNER
    exec sudo --preserve-env=OWNER "$0" "$@"
    return
fi

wget -O remote.yaml $CONFIG_URL

cat <<EOF > config.yaml
EOF
cat remote.yaml >> config.yaml

sed -i "s/^secret: .\+/secret: $PASSWORD/" config.yaml
sed -i "s/address: [0-9.]\+/address: $BIND/" config.yaml
sed -i "s/^external-controller: .\+:9090/external-controller: $BIND:9090/" config.yaml
sed -i "s/listen: .\+:53/listen: $DNS_BIND:53/" config.yaml
sed -i 's/enhanced-mode: fake-ip/enhanced-mode: redir-host/' config.yaml
sed -i 's/auto-route: true/auto-route: false/' config.yaml
sed -i 's/auto-detect-interface: true/auto-detect-interface: false/' config.yaml

if [ -f ./meta-config.local ]; then
    source ./meta-config.local
fi

wget -O- --method=PUT --header="Authorization: Bearer $PASSWORD" --body-data='{"path": "", "payload": ""}' "http://$BIND:9090/configs?force=true" || true

$CHOWN
chmod 777 . providers || true
chmod 666 *.db *.dat providers/*.yaml || true
